# Generated by Django 6.0 on 2026-02-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comentario_autor_comentario_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blog_fotos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='minutos_lectura',
            field=models.IntegerField(default=5, help_text='Tiempo estimado de lectura'),
        ),
        migrations.AddField(
            model_name='post',
            name='resumen',
            field=models.TextField(default='Resumen provisional', help_text='Un pequeño avance para la portada', max_length=500),
            preserve_default=False,
        ),
    ]
